### ISSUE TITLE
blog在产品模式下报错

### ISSUE THREAD

**Issue by xiaohanxu-nick** [Marco2333/react-projects#3]
运行：`node ./server/bin/www` 后打开`http://localhost:3000/`无法显示内容
报错信息为：
```
GET / 304 11.919 ms - -
/Users/Nick/Desktop/react-projects/blog/server/db.js:14
        connection.query(sql, function (err, rows) {
                  ^

TypeError: Cannot read property 'query' of undefined
    at /Users/Nick/Desktop/react-projects/blog/server/db.js:14:19
    at Handshake.onConnect (/Users/Nick/Desktop/react-projects/blog/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.Sequence.end (/Users/Nick/Desktop/react-projects/blog/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Protocol.handleNetworkError (/Users/Nick/Desktop/react-projects/blog/node_modules/mysql/lib/protocol/Protocol.js:363:14)
    at PoolConnection.Connection._handleNetworkError (/Users/Nick/Desktop/react-projects/blog/node_modules/mysql/lib/Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by xiaohanxu-nick** [comment]
好吧，我搞清楚了。
忘记安装MySQL了。
http://blog.csdn.net/kaitlyn2011/article/details/49761509
